name: Lint
on: push
jobs:
  run-lint:
    name: Run lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Dependencies for frontend
        run: npm ci
        working-directory: ./frontend
      - name: Run frontend linters
        run: npm run lint
        working-directory: ./frontend
